# -*- coding: utf-8 -*-
"""Language.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlfMwQht7Qz6_FfuhK7EhZUHvh_z6Tg1
"""

# Install necessary libraries
!pip install transformers sentencepiece --quiet

from transformers import pipeline
from google.colab import files

# Upload the input file
uploaded = files.upload()

# Get the filename (assuming one file uploaded)
filename = list(uploaded.keys())[0]
print(f"Uploaded file: {filename}")

# Ask for source language
source_lang = input("Enter source language ('fr' for French, 'es' for Spanish): ").strip().lower()

# Load the right translator pipeline
if source_lang == 'fr':
    translator = pipeline("translation_fr_to_en")
elif source_lang == 'es':
    translator = pipeline("translation_es_to_en")
else:
    raise ValueError("Unsupported language. Please enter 'fr' or 'es'.")

# Read the file lines
with open(filename, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Translate lines
translated_lines = []
for line in lines:
    line = line.strip()
    if line:
        translation = translator(line, max_length=100)
        translated_text = translation[0]['translation_text']
        translated_lines.append(translated_text)
    else:
        translated_lines.append('')  # preserve empty lines

# Save translations to output file
output_filename = "translated_output.txt"
with open(output_filename, 'w', encoding='utf-8') as f:
    for t_line in translated_lines:
        f.write(t_line + "\n")

print(f"Translation complete! Download the file: {output_filename}")

# Provide download link
files.download(output_filename)

!pip install transformers sentencepiece --quiet
from transformers import pipeline
from google.colab import files

# Upload the input file
uploaded = files.upload()

# Get the uploaded filename
filename = list(uploaded.keys())[0]
print(f"Uploaded file: {filename}")

# Ask for source language
source_lang = input("Enter source language ('fr' for French, 'es' for Spanish): ").strip().lower()

# Select appropriate model
if source_lang == 'fr':
    model_name = "Helsinki-NLP/opus-mt-fr-en"
elif source_lang == 'es':
    model_name = "Helsinki-NLP/opus-mt-es-en"
else:
    raise ValueError("Unsupported language. Use 'fr' or 'es'.")

# Load translator with specified model
translator = pipeline("translation", model=model_name)

# Read the file
with open(filename, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Translate each line
translated_lines = []
for line in lines:
    line = line.strip()
    if line:
        result = translator(line, max_length=100)[0]['translation_text']
        translated_lines.append(result)
    else:
        translated_lines.append('')

# Save output
output_filename = "translated_output.txt"
with open(output_filename, 'w', encoding='utf-8') as f:
    for line in translated_lines:
        f.write(line + "\n")

print(f"Translation completed. Downloading output: {output_filename}")
files.download(output_filename)